import {readFile,writeFile,access} from 'node:fs/promises';
const audit=JSON.parse(await readFile('assets-source/model-audit.json','utf8'));
const notes=JSON.parse(await readFile('assets-source/future-polish-notes.json','utf8'));
const registry=await readFile('src/assets/registry.ts','utf8');
const ids=Object.fromEntries([...registry.matchAll(/["']?([\w.-]+)["']?\s*:\s*\{\s*kind:\s*["']glb["'],\s*url:\s*["']([^"']+)["']/g)].map(m=>[m[2].split('/').pop(),m[1]]));
const titles={
 'cargo-ship':'Navio cargueiro','container-red':'Contêiner vermelho','container-blue':'Contêiner azul','harbor-crane':'Guindaste portuário',
 'townhouse-sage':'Torre curva','townhouse-cream':'Edifício escalonado','townhouse-coral':'Edifício comercial','townhouse-pink':'Edifício com varandas',
 'house-cream':'Casa solar amarela','house-coral':'Casa com jardim na cobertura','house-terrace':'Casa com terraço','house-solar':'Casa solar branca',
 'hospital':'Hospital','school':'Escola','civic':'Prefeitura','office-glass':'Torre de escritórios','factory':'Fábrica','port-warehouse':'Galpão portuário',
 'corner-cafe':'Café','fuel-station':'Estação de recarga','city-bus':'Ônibus elétrico','delivery-truck':'Caminhão elétrico',
 'car-blue':'Carro azul','car-white':'Carro branco','car-coral':'Carro coral','car-gold':'Carro amarelo',
 'train-cab':'Cabine do trem','train-carriage':'Vagão articulado','solar-station':'Estação solar','bus-shelter':'Abrigo de ônibus',
 'tree-palm':'Palmeira','tree-blossom':'Árvore florida','tree-rooftop':'Árvore de terraço','ev-charger':'Carregador','solar-canopy':'Cobertura solar','air-treatment':'Tratamento do ar',
};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=audit.filter(a=>!a.name.endsWith('-low.glb')).map(a=>{
 const file=a.name.replace('.glb',''),id=ids[a.name];if(!id)throw Error(`Modelo sem registro: ${a.name}`);
 return {...a,file,id,title:titles[file]??file.replaceAll('-',' '),polished:!!notes[file],detail:notes[file]??'Conjunto funcional preservado e revisado na paleta da cidade. Materiais e acabamento natural mantêm a função do objeto.',low:audit.find(b=>b.name===file+'-low.glb')};
}).sort((a,b)=>Number(b.polished)-Number(a.polished)||a.title.localeCompare(b.title,'pt-BR'));
for(const row of rows)for(const suffix of ['','-rear','-low'])await access(`docs/screenshots/future/models/${row.id}${suffix}.png`);
const full=rows.reduce((s,r)=>s+r.bytes,0),low=rows.reduce((s,r)=>s+(r.low??r).bytes,0);
const format=n=>n.toLocaleString('pt-BR');
await writeFile('docs/future-catalog.json',JSON.stringify(rows,null,2));
await writeFile('docs/CIDADE-FUTURISTA.html',`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EcoQuest · Cidade futurista</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f2f5ef;color:#183e3c;font:16px/1.55 system-ui}header,main{max-width:1440px;margin:auto;padding:40px}header{padding-bottom:12px}.eyebrow{font-size:12px;letter-spacing:.15em;text-transform:uppercase;color:#447c75}h1{font-size:clamp(32px,4vw,54px);line-height:1.12;margin:14px 0}p{max-width:850px;color:#47655f}.stats{display:flex;gap:24px;flex-wrap:wrap;margin:24px 0}.stats strong{font-size:25px;display:block}.stats span{font-size:13px}.comparison{position:relative;aspect-ratio:1672/941;overflow:hidden;border-radius:16px;background:#9cceb5}.comparison img{position:absolute;width:100%;height:100%;object-fit:cover}.after{clip-path:inset(0 0 0 var(--split,50%))}.comparison:after{content:'';position:absolute;left:var(--split,50%);top:0;bottom:0;width:2px;background:white}.labels{display:flex;justify-content:space-between;font-size:13px}.slider{width:100%;accent-color:#218e94}.controls{position:sticky;top:0;z-index:2;display:flex;flex-wrap:wrap;gap:14px;background:#f2f5eff2;padding:18px 0}label{font-size:13px;display:grid;gap:4px}input,select{padding:10px;border:1px solid #b4ccc1;border-radius:8px;background:white;color:#183e3c;font:inherit}input{width:260px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}article{background:white;border:1px solid #d4e2d9;border-radius:14px;overflow:hidden}.preview{display:block;border:0;padding:0;background:#f3f4eb;width:100%;cursor:zoom-in}.preview img{width:100%;display:block}.content{padding:18px}article h3{margin:0 0 8px}article p{font-size:14px;margin:8px 0}.tag{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#418c79}.meta{font-size:12px;color:#71847d}a{color:#087b86}dialog{border:1px solid #c9d9cf;border-radius:14px;max-width:95vw;width:970px;padding:24px}dialog::backdrop{background:#0b2626c9}dialog img{width:100%;max-height:72vh;object-fit:contain}dialog button{float:right;padding:8px 16px;cursor:pointer}footer{padding:32px;text-align:center;color:#647e74;font-size:13px}[hidden]{display:none!important}@media(max-width:600px){header,main{padding:22px}.controls label,input,select{width:100%}}</style>
<header><div class="eyebrow">EcoQuest · Arquitetura e acabamento</div><h1>Uma cidade solar,<br>modelo por modelo.</h1><p>Curvas contínuas, vidro azul, coberturas verdes e infraestrutura integrada. A revisão de polimento trata superfícies, junções, espessuras e equipamentos próprios de cada modelo.</p><div class="stats"><div><strong>${Object.keys(notes).length}</strong><span>modelos futuristas polidos</span></div><div><strong>${rows.length}</strong><span>modelos no catálogo</span></div><div><strong>${audit.length-rows.length}</strong><span>variantes leves</span></div><div><strong>${(full/1e6).toFixed(2)} / ${(low/1e6).toFixed(2)} MB</strong><span>catálogo completo / seleção leve</span></div></div><a href="CIDADE-FUTURISTA.md">Ler alterações e validação</a></header>
<main><h2>Antes e depois, na mesma câmera</h2><div class="comparison"><img src="screenshots/future/baseline/city-HIGH.png" alt="Cidade antes da transformação"><img class="after" src="screenshots/future/final/city-HIGH.png" alt="Cidade futurista final"></div><div class="labels"><span>Anterior</span><span>Futurista</span></div><label>Comparar a cidade<input class="slider" type="range" min="0" max="100" value="50" aria-label="Comparar antes e depois"></label>
<h2>Montanha e folhagem</h2><p>O trem chega por um maciço com encostas rochosas e mata. As copas têm folhas desenhadas com nervuras, e os telhados usam grama fina e suave. A água tem variação de profundidade e ondulações. <a href="AGUA-E-VEGETACAO.md">Revisão de água e vegetação</a>.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px"><a href="screenshots/future/final/mountain.png"><img style="width:100%;border-radius:14px" src="screenshots/future/final/mountain.png" alt="Montanha completa e ferrovia" loading="lazy"></a><a href="screenshots/future/nature/leaves-HIGH.png"><img style="width:100%;border-radius:14px" src="screenshots/future/nature/leaves-HIGH.png" alt="Textura das folhas no parque" loading="lazy"></a></div><h2>Porto e limites de exploração</h2><p>Casco curvo, 44 contêineres no cais, texturas próprias de cada material e câmera limitada por toda a área visível. <a href="PORTO-E-LIMITES.md">Ver revisão</a>.</p><a href="screenshots/future/port/harbor.png"><img style="width:100%;border-radius:14px" src="screenshots/future/port/harbor.png" alt="Porto com navio polido e pilhas de contêineres" loading="lazy"></a><h2>Catálogo individual</h2><p>Compare frente, verso e versão leve. Clique para ampliar a renderização do GLB real.</p><div class="controls"><label>Buscar modelo<input id="search" type="search" placeholder="Hospital, casa, trem…"></label><label>Conjunto<select id="scope"><option value="polished">Futuristas polidos</option><option value="all">Catálogo completo</option><option value="buildings">Construções</option></select></label><label>Vista<select id="angle"><option value="">Frente · detalhado</option><option value="-rear">Verso · detalhado</option><option value="-low">Frente · leve</option></select></label></div><p id="count" role="status"></p><div class="grid">${rows.map(r=>`<article data-search="${esc(r.title+' '+r.id)}" data-polished="${r.polished}" data-building="${r.id.startsWith('building.')}"><button class="preview" data-id="${r.id}" aria-label="Ampliar ${esc(r.title)}"><img src="screenshots/future/models/${r.id}.png" alt="${esc(r.title)}" loading="lazy" width="480" height="360"></button><div class="content"><span class="tag">${r.polished?'Futurista · polido':'Conjunto complementar'}</span><h3>${esc(r.title)}</h3><p>${esc(r.detail)}</p><p class="meta">${format(r.triangles)} triângulos${r.low?' · leve: '+format(r.low.triangles):''}</p><a href="../public/assets/models/${r.name}">GLB</a> · <a href="../assets-source/${r.file}.blend">Blender</a></div></article>`).join('')}</div></main>
<dialog><button id="close">Fechar</button><h2></h2><img alt=""></dialog><footer>Arquivos renderizados localmente em setembro de 2026. O custo da cena depende da câmera, das instâncias e do perfil gráfico.</footer>
<script>const cards=[...document.querySelectorAll('article')],scope=document.querySelector('#scope'),search=document.querySelector('#search'),angle=document.querySelector('#angle'),dialog=document.querySelector('dialog');function filter(){let count=0;for(const c of cards){c.hidden=!(c.dataset.search.toLowerCase().includes(search.value.toLowerCase())&&(scope.value==='all'||scope.value==='polished'&&c.dataset.polished==='true'||scope.value==='buildings'&&c.dataset.building==='true'));if(!c.hidden)count++;}document.querySelector('#count').textContent=count+' modelos';}search.oninput=filter;scope.onchange=filter;angle.onchange=()=>{for(const c of cards)c.querySelector('img').src='screenshots/future/models/'+c.querySelector('button').dataset.id+angle.value+'.png';};for(const c of cards)c.querySelector('button').onclick=()=>{dialog.querySelector('h2').textContent=c.querySelector('h3').textContent;dialog.querySelector('img').src=c.querySelector('img').src;dialog.querySelector('img').alt=c.querySelector('img').alt;dialog.showModal();};document.querySelector('#close').onclick=()=>dialog.close();document.querySelector('.slider').oninput=e=>document.querySelector('.comparison').style.setProperty('--split',e.target.value+'%');filter();</script></html>`);
console.log(`Galeria: ${rows.length} modelos, ${Object.keys(notes).length} polidos.`);
